name: flights
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cloud_firestore: ^5.4.2
  firebase_core: ^3.5.0
  flutter:
    sdk: flutter
  flutter_gen: ^5.7.0
  flutter_localizations:
    sdk: flutter
  google_maps_flutter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
