repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
  - repo: https://github.com/rhysd/actionlint
    rev: 'v1.7.1'
    hooks:
      - id: actionlint
  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        entry: black --check
        types: [python]
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        language: system
        entry: ruff check .
        types: [python]
  - repo: local
    hooks:
      - id: poetry-update
        name: poetry-update
        language: system
        entry: poetry update
# TODO:  Add buf
