# REALISTICALLY -- most of this should run on PRs before able to push to main
on: # Apply to all pushes to `main`
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
